### ISSUE TITLE
Memory Leak in Live Reconstruction Pipeline

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1771]
**Describe the bug**

If I run [tiltseries_W.tif](https://figshare.com/articles/tiltser_W_tif/2075248) tomviz will consume 17GB of memory when I run SIRT with the Cimmino or Component Average Method. As a reference, the dataset is 2.2MB. Also, this heavy memory consumption occurs when I run TV Minimization or ART (regardless of how many iterations I choose). 

**To Reproduce**
1. Load tiltseries_W.tif 
2. Mark Data as Tilt Series 
3. Run either ART, SIRT or TV Minimization Method.

**Expected behavior**

For tomviz not to take up so much memory. 

**Desktop (please complete the following information):**
 - Operating system: macOS 10.14.2
 - Tomviz version: 1.5.1-17-gc40893a2

**Hardware (please complete the following information):**
 - Device: Macbook Pro
 - Graphics card: Intel Iris Pro 1536 MB

**Comment by cjh1** [comment]
@jtschwar Does the memory usage drop after the pipeline execution is complete?

**Comment by psavery** [comment]
@jtschwar I was able to reproduce this on Ubuntu 18.04 with Tomviz 1.5.1. But it looks to me that the problem went away as of 1.6.0 and/or the nightly builds. Can you give those a try and see if it is fixed for you as well?

**Comment by jtschwar** [comment]
Yeah, this issue should be resolved now. I made some changes to the algorithms so that it's no longer as intensive on the RAM.

**Comment by cryos** [comment]
This may still be an issue, we should spend some time looking at cases where issues persist or close this issue if there are no apparent leaks.

**Comment by cjh1** [comment]
@psavery Can you confirm that this is no longer an issue, if so we can close this issue.

**Comment by psavery** [comment]
I gave it a try on master, and it doesn't look like it is an issue anymore. I think it is fixed.

**Comment by cjh1** [comment]
Thanks @psavery, will close for now. @jtschwar feel free to reopen is you are still seeing an issue.
