### ISSUE TITLE
Tilt axis alignment

### ISSUE THREAD

**Issue by mahsasina** [OpenChemistry/tomviz#540]
The three reconstructions on the bottom become very small and its very difficult to do the tilt axis alignment.

**Comment by Hovden** [comment]
Thanks for reporting this issue. This was recently reported in #538.

We will get it fixed.

**Comment by mahsasina** [comment]
Great, thanks.

**Comment by mathturtle** [comment]
This should be fixed in the latest version as of last Friday.

**Comment by mathturtle** [comment]
@mahsasina So in case noone has given you an update on this, this bug is fixed in the current development build.  So if you download the latest development build binaries it will be fixed.  We are planning to make a bugfix release in the next week to address this and a few other issues that were found in 0.9.0.

**Comment by ercius** [comment]
@mahsasina is at NCEM this week. We were discussing tomviz in general and this bug came up.

It looks like the original bug is fixed now as per #538. However I still see some odd issues with contrast/brightness. The 3 reconstructed slices are mostly washed out. Changing the max/min instensity range in the main GUI window (next to the histogram) affects these images, but only after clicking on the alignment window. I think work for #552 will fix this problem eventually.

**Comment by mathturtle** [comment]
The bugfix release 0.9.1 will be released today/tomorrow and contains the fixes for this.  Or you can download the latest binaries from tomviz.org, those should have that fix too.  It was merged last Friday, but there was a bug that kept the builds from happening until yesterday morning.

**Comment by bdalevin** [comment]
Downloaded the latest binary, and tested out the tilt axis alignment. It's working well for my data.
