### ISSUE TITLE
State file does not save colormap range or opacity settings

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#565]
Windows 10, tomviz 0.9.0 (release)

State files do not reload colormap range and opacity settings. 

I want to recall these settings in the Histogram using a state file to produce a nice visualization:
![clipboard02](https://cloud.githubusercontent.com/assets/15657108/17787261/458fe736-653d-11e6-9a74-0afc007b6d9d.png)

However, saving a state file and reloading it sets the opacity and range to the full range:
![clipboard01](https://cloud.githubusercontent.com/assets/15657108/17787278/5518830c-653d-11e6-8ee1-6f851c562157.png)

**Comment by Hovden** [comment]
This is important for reproducibility

**Comment by mathturtle** [comment]
I'm going to look at this today.

**Comment by cquammen** [comment]
Fix was merged.

**Comment by ElliotPadgett** [comment]
This only looks half fixed to me.  The state file now saves the color map but fails to save the opacity settings.

**Comment by ercius** [comment]
I've also noticed this in recent Windows builds but was holding off
reporting it until I could get the newest nightly from Cdash.

**Comment by ElliotPadgett** [comment]
@cquammen @mathturtle Any comment on this?  Altering the opacity function for a volume rendering is very common, so this issue is really a nuisance for making or sharing volume renderings.

**Comment by cquammen** [comment]
Sorry, not ignoring. I'll take a look later today.

**Comment by ElliotPadgett** [comment]
Thanks!

**Comment by cquammen** [comment]
Update: it seems that only the default scalar opacity function is being saved to the state file, which means the `DataSource` has a reference to the wrong one. Looking into why.

**Comment by cquammen** [comment]
Actually, I was wrong in my previous comment. The `ScalarOpacityFunction` proxy is the same in the `DataSource` (when a separate color map is not used).

The actual problem is that the `HistogramWidget` modifies the client-side `vtkPiecewiseFunction`. However, the opacity map values never make it back from the VTK object to the proxy.

A good question is: how does it work with the color map, which works essentially the same way? I'm not sure yet. I have a quick hack in mind that should at least solve this problem, which I will push up sometime today, hopefully.

**Comment by cquammen** [comment]
Hi folks, this should be fixed in #685, which has been merged to master. Please reopen if you have any problems.

**Comment by ElliotPadgett** [comment]
Just tried this in the latest nightly build and now neither the color map nor the opacity setting is saved and restored.  Contour rendering with single color specified don't remember their color either.  Is the fix supposed to be in today's nightly?

**Comment by cquammen** [comment]
I should have some time this afternoon to look at this.

**Comment by ElliotPadgett** [comment]
@yijiang1 told me that it works in his build, but doesn't seem to in the binary, in case that helps with tracking it down.

**Comment by cquammen** [comment]
Is this still not working in the nightly build?

**Comment by ElliotPadgett** [comment]
Actually we misidentified this before.  The issue is with the "separate color map" option.

The builds are consistent, and tomviz is correctly saving changes to the global color map.  The problem is that when you check "separate color map" for a visualization and then save/restore tomviz forgets that that box is checked and what color map was set up for it.  @yijiang1 also points out that this seems to work for contour renderings but not for volume renderings.

**Comment by ElliotPadgett** [comment]
No problem for orthoslices either.

**Comment by cquammen** [comment]
Great, thanks for the detailed update. That should make it a lot easier to track down.

**Comment by cryos** [comment]
This is a known issue I introduced, Rob wanted the new volume features, I need to figure out how to save that stuff correctly as after the changes to volume module.

**Comment by cquammen** [comment]
Ah, okay. Thanks @cryos.

**Comment by cryos** [comment]
#723 should address this issue, and does in my local testing. Still looking into the other issue that looks a little trickier.

**Comment by cryos** [comment]
I fixed half of the issue, @cquammen you added the support for opacity saving on the global color map. Maybe this needs adding to a more central spot so it can be used by both global and separate color maps?

**Comment by cquammen** [comment]
Yes, I was thinking that should be done. Will take a look.

**Comment by cquammen** [comment]
Okay, final bits should be fixed in #733 for the global and separate color maps.

**Comment by cryos** [comment]
Closing this now that #733 is merged, please let us know if the latest binaries from this evening still cause issues.

**Comment by JeremyHorst** [comment]
This issue is still occurring on an MacOS with 1.2.1. State save does not keep the color map nor opacity for volume. Does not seem to correspond to separate color maps.
Also there is no way to save the color map; I will open this as a separate issue, though it is somewhat related.
